### ISSUE TITLE
Set up enviroment

### ISSUE THREAD

**Issue by hidetora-max** [hidetora-max/DOKODEMO#1]
# Todo

- [ ] Dockerfile and docker-compose.yml

- [ ] Change database to PostgreSQL

- [ ] Change language to Japanese
